Repository UMC-DEMO-PROJECT/Chat-Sul, pull requests merged in 2025-02, with the labels that each got.

#73 Feat/lostlist 분실물 관련 api 수정
  src/components/Lostwriting/LostWritingForm.tsx
  src/shared/api/lost.tsx
  yarn.lock
Labels: chore

#74 Feat/lostitem 분실물 수취 상태 변경 버튼 추가
  src/pages/Owner/LostItem/LostItem_Owner.tsx
  src/pages/User/LostItem/.keep
Labels: feat

#78 feat: shop 페이지 완성
  public/icons/checked.svg
  public/icons/lostlist.svg
  public/icons/menu.svg
  public/icons/reserve.svg
  src/App.tsx
  src/components/User/Shop/shoppingCard.tsx
  src/pages/Owner/Shop/OwnerShop.tsx
  src/pages/User/Shop/userShop.tsx
  src/shared/ui/Icon/Icon.tsx
Labels: feat

#80 Feat/lost api 다이나믹 라우팅 추가 및 분실물 수정 api 추가
  src/App.tsx
  src/components/Lost/Lostlist.tsx
  src/components/LostItem/Option.tsx
  src/components/Lostwriting/LostWritingForm.tsx
  src/hooks/useGetInfiniteLostList.ts
  src/pages/Owner/LostItem/LostItem_Owner.tsx
  src/shared/api/lost.tsx
  src/shared/type/LostType.ts
Labels: feat

#81 refactor/owner,user reserve listAPI추가,Topbar수정
  public/icons/cancel.svg
  src/components/Owner/ReserveList/AlertContainer.tsx
  src/components/Owner/ReserveList/ReserveList.tsx
  src/components/Owner/ReserveList/types/TReserveList.ts
  src/components/Owner/ReserveList/types/dataTypes.ts
  src/components/Owner/ReserveList/ui/Alert/AlertContainer.tsx
  src/components/Owner/ReserveList/ui/Alert/WaitingConfirmation.tsx
  src/components/Owner/ReserveList/ui/Alert/WaitingDepositAlert.tsx
  src/components/Owner/ReserveList/ui/TagBar/TagBar.tsx
  src/components/User/ReserveList/type/TReserveList.ts
  src/components/User/ReserveList/ui/Alert/AlertContainer.tsx
  src/components/User/ReserveList/ui/Alert/CancelledAlert.tsx
  src/components/User/ReserveList/ui/Alert/ConfirmedAlert.tsx
  src/components/User/ReserveList/ui/Alert/ReservationCancelAlert.tsx
  src/components/User/ReserveList/ui/Alert/ReservationCancelFailAlert.tsx
  src/components/User/ReserveList/ui/Alert/WaitingDepositAlert.tsx
  src/components/User/ReserveList/ui/ReserveListContainer.tsx
  src/shared/api/reservation.ts
  src/shared/ui/Modal/exampleOne.tsx
  src/shared/ui/Modal/exampleTwo.tsx
  src/shared/ui/Post/example.tsx
  src/shared/ui/RentalCard/RentalCard.tsx
  src/shared/ui/RentalCard/RentarCardSkeleton.tsx
  src/shared/ui/TopBar/TopBar.tsx
Labels: feat, refactor

#84 Feat/lost api
  src/pages/Main/kakao.tsx
Labels: chore

#90 feat: menu 페이지 생성
  package.json
  public/icons/plus.svg
  src/App.tsx
  src/components/Lostwriting/LostWritingForm.tsx
  src/components/Owner/Menu/uploadingMenu.tsx
  src/components/Owner/ReserveList/ui/TagBar/TagBar.tsx
  src/components/Register/RegisterForm.tsx
  src/components/Register/SocialRegisterForm.tsx
  src/components/User/Menu/userMenu.tsx
  src/components/User/ReserveForm/ui/ReserveFormContainer.tsx
  src/components/User/ReserveList/ui/ReserveListContainer.tsx
  src/components/User/ReserveSuccess/ReserveSuccessContainer.tsx
  src/components/Validate/ValidateForm.tsx
  src/index.css
  src/pages/Owner/LostItem/LostItem_Owner.tsx
  src/pages/Owner/LostList/LostList_Owner.tsx
  src/pages/Owner/MenuList/Menu_Owner.tsx
  src/pages/User/LostItem/LostItem.tsx
  src/pages/User/LostList/LostList.tsx
  src/pages/User/MenuList/Menu.tsx
  src/pages/User/Shop/userShop.tsx
  src/shared/api/menu.ts
  src/shared/api/venue.ts
  src/shared/ui/Input/AccountInput.tsx
  src/shared/ui/TopBar/TopBar.tsx
  tailwind.config.js
  yarn.lock
Labels: feat, refactor

#92 refactor/user-reserve-list구조변경
  src/components/User/ReserveList/context/SelectedModalDataContext.tsx
  src/components/User/ReserveList/context/SelectedModalDataContextProvider.tsx
  src/components/User/ReserveList/hooks/useGetReserveListInfinity.ts
  src/components/User/ReserveList/hooks/useReserveListValidateQuery.ts
  src/components/User/ReserveList/type/TReserveList.ts
  src/components/User/ReserveList/ui/Alert/AlertContainer.tsx
  src/components/User/ReserveList/ui/Alert/ReservationCancelAlert.tsx
  src/components/User/ReserveList/ui/Alert/ReservationCancelFailAlert.tsx
  src/components/User/ReserveList/ui/Alert/WaitingConfirmation.tsx
  src/components/User/ReserveList/ui/Alert/WaitingDepositAlert.tsx
  src/components/User/ReserveList/ui/ReserveListContainer.tsx
  src/shared/ui/Modal/ModalLayout/ModalLayout.tsx
Labels: refactor

#93 Feat/lost api LostLIst 관련 cicd 에러 코드 수정
  src/components/Lost/Lostlist.tsx
  src/shared/type/LostType.ts
Labels: refactor

#95 feat: 분실물 수취 변경 모달 추가
  src/components/LostItem/Button_Modal.tsx
  src/pages/Owner/LostItem/LostItem_Owner.tsx
  yarn.lock
Labels: feat

#96 refactor:owner-reserve-list코드개선
  src/components/Owner/ReserveList/ReserveList.tsx
  src/components/Owner/ReserveList/context/SelectedModalDataContext.ts
  src/components/Owner/ReserveList/context/SelectedModalDataContextProvider.tsx
  src/components/Owner/ReserveList/hooks/useGetOwnerReservationInfinity.ts
  src/components/Owner/ReserveList/hooks/useOwnerReserveListValidateQuery.ts
  src/components/Owner/ReserveList/types/TReserveList.ts
  src/components/Owner/ReserveList/ui/Alert/AlertContainer.tsx
  src/components/Owner/ReserveList/ui/Alert/WaitingConfirmation.tsx
  src/components/Owner/ReserveList/ui/Alert/WaitingDepositAlert.tsx
  src/components/Owner/ReserveList/ui/TagBar/TagBar.tsx
Labels: refactor

#98 Feat/kakaomap 최종
  index.html
  src/pages/Main/kakao.tsx
  src/shared/ui/Map/example33.tsx
Labels: feat

#99 refactor/reserve form,reserve list
  src/App.tsx
  src/components/Owner/ReserveList/ReserveList.tsx
  src/components/Owner/ReserveList/ui/Alert/WaitingConfirmation.tsx
  src/components/Owner/ReserveList/ui/Alert/WaitingDepositAlert.tsx
  src/components/User/ReserveForm/types/types.ts
  src/components/User/ReserveForm/ui/ReserveFormContainer.tsx
  src/components/User/ReserveSuccess/ReserveSuccessContainer.tsx
  src/pages/User/ReserveForm/.keep
Labels: refactor

#101 refactor : reserve-form에러처리,로딩처리,구조개선
  src/App.tsx
  src/components/Owner/ReserveList/context/SelectedModalDataContext.ts
  src/components/Owner/ReserveList/hooks/useGetOwnerReservationInfinity.ts
  src/components/Owner/ReserveList/hooks/useOwnerReserveListValidateQuery.ts
  src/components/Owner/ReserveList/ui/Alert/WaitingConfirmation.tsx
  src/components/Owner/ReserveList/ui/Alert/WaitingDepositAlert.tsx
  src/components/User/ReserveForm/ReserveForm.tsx
  src/components/User/ReserveForm/ReserveFormContainer.tsx
  src/components/User/ReserveForm/ReserveFormState.tsx
  src/components/User/ReserveForm/types/types.ts
  src/components/User/ReserveList/ui/Alert/ReservationCancelAlert.tsx
  src/components/User/ReserveList/ui/Alert/WaitingDepositAlert.tsx
  src/components/User/ReserveList/ui/ReserveListContainer.tsx
  src/components/User/ReserveSuccess/ReserveSuccessContainer.tsx
  src/components/User/ReserveSuccess/SuccessMessage.tsx
  src/pages/User/ReserveForm/ReserveForm.tsx
  src/shared/ui/Modal/Alert/AlertOneButton.tsx
  src/shared/ui/TopBar/TopBar.tsx
Labels: feat, refactor

#103 Feat/lost api 분실물 글 등록, 수정 API
  src/components/Lost/user/Lostlist_user.tsx
  src/components/LostItem/owner/LostItem.tsx
  src/components/LostItem/user/LostItem.tsx
  src/components/LostModify/LostModifyForm.tsx
  src/components/Lostwriting/LostWritingForm.tsx
  src/pages/User/LostList/LostList.tsx
  src/shared/api/lost.tsx
  src/shared/type/LostType.ts
Labels: refactor

#106 Feat/lost api 분실물 목록 페이지의 검색 기능
  src/components/Lost/owner/Lostlist.tsx
  src/components/Lost/user/Lostlist_user.tsx
  src/components/LostItem/Button_Modal.tsx
  src/pages/Owner/LostList/LostList_Owner.tsx
  src/pages/Owner/Shop/OwnerShop.tsx
  src/shared/ui/TopBar/TopBar.tsx
Labels: refactor

#107 refactor: 메인 페이지에서 OWNER일때 가게버튼 아이콘 수정
  public/icons/Storenoplus.svg
  src/pages/Main/kakao.tsx
Labels: refactor

#108 Feat/lost api 검색창 코드 수정
  src/components/Lost/LostInput.tsx
Labels: refactor

#110 feat: 분실물 목록 페이지에 스켈레톤 UI 추가
  src/components/Lost/owner/Lostlist.tsx
  src/components/Lost/user/Lostlist_user.tsx
  src/shared/ui/Post/PostSkeleton.tsx
Labels: feat

#111 refactor: 분실물 아이템 페이지 topbar 뒤로가기 경로 수정
  src/pages/Owner/LostItem/LostItem_Owner.tsx
  src/shared/ui/TopBar/TopBar.tsx
Labels: refactor

#115 Feat/lost api
  src/components/User/Menu/userMenu.tsx
Labels: refactor

#116 refactor: topbar, 분실물 상세 페이지 옵션, 모달에 z-index 추가
  src/components/LostItem/Option.tsx
  src/shared/ui/Modal/ModalLayout/ModalLayout.tsx
  src/shared/ui/TopBar/TopBar.tsx
Labels: refactor

#117 Feat/lost api
  src/components/Login/LoginForm.tsx
  src/components/User/Menu/userMenu.tsx
  src/pages/Login/SocialLogin/SocialAccess.tsx
Labels: refactor

#119 refactor/user reserve list
  src/components/User/ReserveForm/ui/Calendar/CustomCalender.tsx
  src/components/User/ReserveList/ui/Alert/WaitingDepositAlert.tsx
Labels: refactor
