Repository UMC-DEMO-PROJECT/Chat-Sul, pull requests merged in 2025-01, with the labels that each got.

#5 chore: React-Router-Dom 임시 설정
  eslint.config.js
  package.json
  postcss.config.js
  src/index.css
  src/shared/Router.tsx
  tailwind.config.js
  yarn.lock
Labels: chore

#12 feat : (Message, Menu, Date, Post, TopBar)생성
  src/shared/@common/ui/Menu/Menu.tsx
  src/shared/@common/ui/Message/Message.tsx
  src/shared/@common/ui/Post/Post.tsx
  src/shared/@common/ui/TopBar/TopBar.tsx
Labels: feat

#9 feat: tailwind공용Color설정
  tailwind.config.js
Labels: feat

#13 feat: Input Component 생성
  postcss.config.js
  src/shared/@common/ui/Input/Input.tsx
  src/shared/@common/ui/Input/example.tsx
  src/shared/@common/ui/Menu/Menu.tsx
  src/shared/@common/ui/Message/Message.tsx
  src/shared/@common/ui/Post/Post.tsx
  src/shared/@common/ui/TopBar/TopBar.tsx
  src/shared/Router.tsx
  tailwind.config.js
Labels: feat

#10 feat: 버튼 컴포넌트 생성
  package.json
  src/components/button.tsx
  yarn.lock
Labels: feat

#20 chore: Layout수정, 폰트수정
  src/index.css
Labels: chore

#18 Feat/button 1
  src/components/button.tsx
Labels: chore

#22 feat: login 페이지 추가 기능 구현
  src/components/Login/LoginForm.tsx
  src/components/Login/SocialLogin.tsx
  src/components/button.tsx
  src/pages/Login/Login.tsx
Labels: feat, refactor

#24 feat:alert버튼 2개, 1개버전, 대관신청확인페이지
  public/icons/check-one.svg
  src/App.tsx
  src/components/User/ReserveForm/.keep
  src/components/User/ReserveList/ReserveListContainer.tsx
  src/components/User/ReserveList/TmpRentarCard.tsx
  src/components/User/ReserveSuccess/ReserveSuccessContainer.tsx
  src/components/User/ReserveSuccess/SuccessMessage.tsx
  src/index.css
  src/pages/User/ReserveList/ReserveList.tsx
  src/pages/User/ReserveSuccess/ReserveSuccess.tsx
  src/shared/ui/Modal/Alert/AlertOneButton.tsx
  src/shared/ui/Modal/Alert/AlertTwoButton.tsx
  src/shared/ui/Modal/ModalLayout/ModalLayout.tsx
  src/shared/ui/Modal/exampleOne.tsx
  src/shared/ui/Modal/exampleTwo.tsx
  tailwind.config.js
Labels: feat

#28 refactor:Menu랑 Post를 제가 이름을 반대로 해놨어서 제대로 수정
  src/shared/ui/Menu/Menu.tsx
  src/shared/ui/Menu/example.tsx
  src/shared/ui/Post/Post.tsx
  src/shared/ui/Post/example.tsx
Labels: refactor

#35 feat: Register 페이지 구현
  src/App.tsx
  src/components/Login/LoginForm.tsx
  src/components/Register/RegisterForm.tsx
  src/components/Register/RegisterTitle.tsx
  src/index.css
  src/pages/Register/Register.tsx
  src/shared/ui/Input/EmailInput.tsx
  src/shared/ui/Input/PasswordCheckInput.tsx
Labels: feat, chore

#38 refactor: Input Width 수정
  src/shared/ui/Input/Input.tsx
Labels: refactor

#39 refactor:post width랑 border색수정
  src/shared/ui/Post/Post.tsx
Labels: refactor

#40 Feat/lostlist 분실물 목록 페이지 input 넓이 코드 수정
  package.json
  postcss.config.js
  public/icons/check-one.svg
  src/App.css
  src/App.tsx
  src/Layout.tsx
  src/assets/lostItem.svg
  src/components/Login/LoginForm.tsx
  src/components/Login/SocialLogin.tsx
  src/components/Lost/LostInput.tsx
  src/components/Lost/Lostlist.tsx
  src/components/Lost/mock/LostListData.ts
  src/components/LostItem/LostItem.tsx
  src/components/Lostwriting/LostWritingForm.tsx
  src/components/Register/RegisterForm.tsx
  src/components/Register/RegisterTitle.tsx
  src/components/User/ReserveForm/.keep
  src/components/User/ReserveList/ReserveListContainer.tsx
  src/components/User/ReserveList/TmpRentarCard.tsx
  src/components/User/ReserveSuccess/ReserveSuccessContainer.tsx
  src/components/User/ReserveSuccess/SuccessMessage.tsx
  src/components/button.tsx
  src/index.css
  src/pages/Login/Login.tsx
  src/pages/Owner/LostForm/LostWriting.tsx
  src/pages/Register/Register.tsx
  src/pages/User/LostItem/LostItem.tsx
  src/pages/User/LostList/LostList.tsx
  src/pages/User/ReserveList/ReserveList.tsx
  src/pages/User/ReserveSuccess/ReserveSuccess.tsx
  src/shared/Router.tsx
  src/shared/api/mock/LostItemData.ts
  src/shared/api/mock/LostListData.ts
  src/shared/ui/Input/EmailInput.tsx
  src/shared/ui/Input/Input.tsx
  src/shared/ui/Input/PasswordCheckInput.tsx
  src/shared/ui/Input/example.tsx
  src/shared/ui/Menu/Menu.tsx
  src/shared/ui/Menu/example.tsx
  src/shared/ui/Message/Message.tsx
  src/shared/ui/Modal/Alert/AlertOneButton.tsx
  src/shared/ui/Modal/Alert/AlertTwoButton.tsx
  src/shared/ui/Modal/ModalLayout/ModalLayout.tsx
  src/shared/ui/Modal/exampleOne.tsx
  src/shared/ui/Modal/exampleTwo.tsx
  src/shared/ui/Post/Post.tsx
  src/shared/ui/Post/example.tsx
  src/shared/ui/TopBar/TopBar.tsx
  src/shared/ui/TopBar/example.tsx
  tailwind.config.js
  yarn.lock
Labels: chore

#42 chore:CI/CD deploy.yml추가
  .github/workflows/deploy.yml
  src/components/Lost/LostInput.tsx
  src/components/Lost/Lostlist.tsx
  src/pages/User/LostList/LostList.tsx
Labels: chore

#34 feat: Icon-RentalCard-DropDown-map 공용 컴포넌트 생성
  index.html
  src/shared/ui/DropDown/DropDown.tsx
  src/shared/ui/DropDown/example.tsx
  src/shared/ui/DropDown/example1.tsx
  src/shared/ui/Icon+RentalCard+Map+DropDown.tsx
  src/shared/ui/Icon/Icon.tsx
  src/shared/ui/Icon/example.tsx
  src/shared/ui/Icon/example1.tsx
  src/shared/ui/Map/Map.tsx
  src/shared/ui/Map/example.tsx
  src/shared/ui/Map/example1.tsx
  src/shared/ui/RentalCard/RentalCard.tsx
  src/shared/ui/RentalCard/example.tsx
  src/shared/ui/RentalCard/example1.tsx
Labels: feat

#45 feat: Validate 페이지 구현
  public/icons/correct-icon.svg
  public/icons/down.svg
  public/icons/error-icon.svg
  public/icons/kakao.svg
  public/icons/naver.svg
  src/App.tsx
  src/components/Login/LoginForm.tsx
  src/components/Login/SocialLogin.tsx
  src/components/Lostwriting/LostWritingForm.tsx
  src/components/Register/RegisterForm.tsx
  src/components/Register/RegisterTitle.tsx
  src/components/Validate/ValidateForm.tsx
  src/pages/Owner/LostForm/LostWriting.tsx
  src/pages/Register/Register.tsx
  src/pages/Validate/Validate.tsx
  src/shared/@common/Title.tsx
  src/shared/ui/Button/button.tsx
  src/shared/ui/Icon+RentalCard+Map+DropDown.tsx
  src/shared/ui/Icon/Icon.tsx
  src/shared/ui/Icon/example.tsx
  src/shared/ui/Icon/example1.tsx
  src/shared/ui/Input/AccountInput.tsx
  src/shared/ui/Input/Input.tsx
  src/shared/ui/Map/Map.tsx
  src/shared/ui/Map/example.tsx
  src/shared/ui/Map/example1.tsx
  src/shared/ui/Message/Message.tsx
  src/shared/ui/Modal/Alert/AlertOneButton.tsx
  src/shared/ui/Modal/Alert/AlertTwoButton.tsx
  src/shared/ui/RentalCard/RentalCard.tsx
  src/shared/ui/RentalCard/example.tsx
  src/shared/ui/RentalCard/example1.tsx
  tsconfig.json
Labels: feat, refactor

#50 feat:유저대관신청레이아웃완성
  package.json
  public/icons/back.svg
  public/icons/down.svg
  public/icons/forth.svg
  src/App.tsx
  src/components/User/ReserveForm/.keep
  src/components/User/ReserveForm/Calendar/Calendar.css
  src/components/User/ReserveForm/Calendar/CustomCalender.tsx
  src/components/User/ReserveForm/DropDown/DropDown.tsx
  src/components/User/ReserveForm/DropDown/Menu.tsx
  src/components/User/ReserveForm/Input/ViewOnlyInPut.tsx
  src/components/User/ReserveForm/Input/ViewOnlyInputContainer.tsx
  src/components/User/ReserveForm/ModalContents/ModalContents.tsx
  src/components/User/ReserveForm/ReserveFormContainer.tsx
  src/index.css
  src/pages/User/ReserveForm/ReserveForm.tsx
  yarn.lock
Labels: feat

#53 refactor:reserve form buttom 위치가 바뀐거 적용했습니다.
  src/components/User/ReserveForm/ReserveFormContainer.tsx
Labels: refactor

#51 Feat/lostitem 분실물 상세 페이지 옵션 아이콘 및 삭제 모달 추가
  public/icons/Option.svg
  src/App.tsx
  src/components/LostItem/Option.tsx
  src/pages/Owner/LostItem/LostItem_Owner.tsx
  src/shared/ui/Modal/Alert/AlertTwoButton.tsx
  src/shared/ui/Modal/exampleTwo.tsx
Labels: feat

#52 Feat/lostlist 분실물 목록 페이지
  src/components/Lost/LostInput.tsx
  src/components/Lost/mock/LostListData.ts
  src/shared/ui/Post/Post.tsx
Labels: chore

#54 feat:reserve list레이아웃 완성
  public/icons/calendar.svg
  public/icons/person.svg
  src/components/User/ReserveList/AlertContainer.tsx
  src/components/User/ReserveList/ReserveListContainer.tsx
  src/shared/ui/RentalCard/RentalCard.tsx
  src/shared/ui/RentalCard/example1.tsx
Labels: feat

#55 Feat/lostwriting 분실물 글 작성 페이지
  src/App.tsx
  src/components/Lostwriting/LostWritingForm.tsx
  src/pages/Owner/LostForm/.keep
  src/pages/Owner/LostForm/LostWriting.tsx
Labels: feat

#46 api: API 임시 작업
  index.html
  package.json
  src/components/Login/LoginForm.tsx
  src/components/Register/RegisterForm.tsx
  src/shared/api/common/axiosInstance.ts
  src/shared/api/membersApi.ts
  src/shared/api/reservation.ts
  src/shared/api/token.ts
  src/shared/api/venue.ts
  yarn.lock
Labels: feat

#57 refactor:reserveList AlertContainer오류수정
  src/components/User/ReserveList/AlertContainer.tsx
  src/index.css
  src/shared/ui/TopBar/TopBar.tsx
Labels: refactor

#59 Feat/lostitem 임시 글꼴 삭제 및 topbar font-weigth 추가
  src/components/LostItem/LostItem.tsx
  src/index.css
Labels: chore

#58 fix: api 수정, 에러 수정
  src/components/Login/LoginForm.tsx
  src/components/Register/RegisterForm.tsx
  src/pages/Register/Register.tsx
  src/shared/ui/DropDown/example.tsx
  src/shared/ui/DropDown/example1.tsx
  src/shared/ui/Map/Map.tsx
  src/shared/ui/Map/example.tsx
  src/shared/ui/Map/example1.tsx
Labels: refactor

#62 Feat/lostlist 절대 경로 추가
  package.json
  src/components/Lost/LostInput.tsx
  src/components/Lost/Lostlist.tsx
  src/pages/User/LostList/LostList.tsx
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: chore

#64 Feat/lostlist 분실물 목록 페이지 페이지네이션 임시 추가 및 검색된 분실물 없을 때 추가
  public/icons/Exclamation.svg
  public/icons/left.svg
  public/icons/right.svg
  src/components/Lost/Lostlist.tsx
  src/components/Lost/Pagination.tsx
  src/pages/Owner/LostList/LostList_Owner.tsx
  src/pages/User/LostList/LostList.tsx
Labels: feat

#66 feat/map
  src/shared/ui/Map/Map.tsx
Labels: feat

#65 chore: Pagination 컴포넌트 파일 이름 변경
  src/pages/User/LostList/LostList.tsx
Labels: chore

#67 refactor:reserveListFormAPI연동
  package.json
  public/icons/spinner.svg
  src/App.tsx
  src/components/User/ReserveForm/ReserveFormContainer.tsx
  src/components/User/ReserveForm/hooks/useReservationForm.ts
  src/components/User/ReserveForm/types/types.ts
  src/components/User/ReserveForm/ui/Calendar/Calendar.css
  src/components/User/ReserveForm/ui/Calendar/CustomCalender.tsx
  src/components/User/ReserveForm/ui/DropDown/DropDown.tsx
  src/components/User/ReserveForm/ui/DropDown/Menu.tsx
  src/components/User/ReserveForm/ui/Input/ViewOnlyInPut.tsx
  src/components/User/ReserveForm/ui/Input/ViewOnlyInputContainer.tsx
  src/components/User/ReserveForm/ui/ModalContents/ModalContents.tsx
  src/components/User/ReserveForm/ui/ReserveFormContainer.tsx
  src/components/User/ReserveSuccess/ReserveSuccessContainer.tsx
  src/components/User/ReserveSuccess/SuccessMessage.tsx
  src/pages/User/ReserveForm/ReserveForm.tsx
  src/shared/api/reservation.ts
  src/shared/ui/Modal/Alert/AlertOneButton.tsx
  yarn.lock
Labels: refactor

#68 feat: 소셜 로그인 페이지 생성
  src/App.tsx
  src/components/Login/LoginForm.tsx
  src/components/Register/SocialRegisterForm.tsx
  src/pages/Register/SocialRegister/SocialRegister.tsx
  src/shared/api/membersApi.ts
Labels: feat

#70 feat:reserve list api조회추가
  package.json
  src/App.tsx
  src/components/User/ReserveList/AlertContainer.tsx
  src/components/User/ReserveList/ReserveListContainer.tsx
  src/components/User/ReserveList/ReserveListPresentor.tsx
  src/components/User/ReserveList/type/TReserveList.ts
  src/components/User/ReserveList/ui/Alert/AlertContainer.tsx
  src/components/User/ReserveList/ui/Alert/CancelledAlert.tsx
  src/components/User/ReserveList/ui/Alert/ConfirmedAlert.tsx
  src/components/User/ReserveList/ui/Alert/WaitingConfirmation.tsx
  src/components/User/ReserveList/ui/Alert/WaitingDepositAlert.tsx
  src/components/User/ReserveList/ui/ReserveListContainer.tsx
  src/components/User/ReserveSuccess/ReserveSuccessContainer.tsx
  src/pages/Owner/Reserve/.keep
  src/pages/User/ReserveList/ReserveList.tsx
  src/shared/api/reservation.ts
  src/shared/ui/RentalCard/RentalCard.tsx
  src/utils/.keep
  src/utils/dateToFormattedKorean.ts
  yarn.lock
Labels: feat

#72 feat: 사업자 인증 페이지 구현 및 Landing 페이지 적용 완료
  index.html
  public/icons/logo.svg
  src/App.tsx
  src/components/Login/LoginForm.tsx
  src/components/Validate/ValidateForm.tsx
  src/components/Validate/type/daum.d.ts
  src/pages/Login/Login.tsx
  src/shared/ui/DropDown/DropDown.tsx
  src/shared/ui/Icon/Icon.tsx
  src/shared/ui/Input/AccountInput.tsx
  src/shared/ui/Input/Input.tsx
Labels: feat

#69 Feat/lostlist 분실물 관련 API 연결 코드 추가
  package.json
  src/components/Lost/Lostlist.tsx
  src/components/Lost/Pagination.tsx
  src/components/LostItem/LostItem.tsx
  src/components/LostItem/Option.tsx
  src/components/Lostwriting/LostWritingForm.tsx
  src/hooks/useGetInfiniteLostList.ts
  src/pages/Owner/LostForm/LostWriting.tsx
  src/pages/User/LostList/LostList.tsx
  src/shared/api/lost.tsx
  src/shared/api/mock/LostListData.ts
  src/shared/type/LostType.ts
  src/shared/ui/Post/Post.tsx
  yarn.lock
Labels: feat
